// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: colony.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Colony {

  /// <summary>Holder for reflection information generated from colony.proto</summary>
  public static partial class ColonyReflection {

    #region Descriptor
    /// <summary>File descriptor for colony.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ColonyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxjb2xvbnkucHJvdG8SBmNvbG9ueRoOdHJhZGFibGUucHJvdG8i5AEKCkNv",
            "bG9ueURhdGESEAoIQ29sb255SWQYASABKAkSDAoETmFtZRgCIAEoCRITCgtG",
            "YWN0aW9uTmFtZRgDIAEoCRINCgVNYXBJZBgJIAEoBRIMCgRUaWNrGAQgASgF",
            "EhMKC1VzZWREZXZNb2RlGAUgASgIEhMKC0dhbWVWZXJzaW9uGAYgASgJEiYK",
            "CFBsYXRmb3JtGAcgASgOMhQuY29sb255LlBsYXRmb3JtRW51bRISCgpDcmVh",
            "dGVEYXRlGAggASgDEgwKBFNlZWQYCiABKAkSEAoITG9jYXRpb24YCyABKAki",
            "TQoTQ29sb255Q3JlYXRlUmVxdWVzdBIUCgxDbGllbnRCaW5kSWQYASABKAkS",
            "IAoEZGF0YRgCIAEoCzISLmNvbG9ueS5Db2xvbnlEYXRhIk0KE0NvbG9ueVVw",
            "ZGF0ZVJlcXVlc3QSFAoMQ2xpZW50QmluZElkGAEgASgJEiAKBERhdGEYAyAB",
            "KAsyEi5jb2xvbnkuQ29sb255RGF0YSI6ChBDb2xvbnlHZXRSZXF1ZXN0EhQK",
            "DENsaWVudEJpbmRJZBgBIAEoCRIQCghDb2xvbnlJZBgCIAEoCSJPChRDb2xv",
            "bnlNb2RzU2V0UmVxdWVzdBIUCgxDbGllbnRCaW5kSWQYASABKAkSEAoIQ29s",
            "b255SWQYAiABKAkSDwoHTW9kTmFtZRgDIAMoCSIUChJDb2xvbnlNb2RzU2V0",
            "UmVwbHkifwoYQ29sb255VHJhZGFibGVTZXRSZXF1ZXN0EhQKDENsaWVudEJp",
            "bmRJZBgBIAEoCRIQCghDb2xvbnlJZBgCIAEoCRImCgRpdGVtGAMgAygLMhgu",
            "dHJhZGFibGUuQ29sb255VHJhZGFibGUSEwoLRmluYWxQYWNrZXQYCiABKAgi",
            "GAoWQ29sb255VHJhZGFibGVTZXRSZXBseSo8CgxQbGF0Zm9ybUVudW0SCwoH",
            "VW5rbm93bhAAEgsKB1dpbmRvd3MQARIJCgVMaW51eBACEgcKA01hYxADMtkC",
            "Cg1Db2xvbnlTZXJ2aWNlEjsKBkNyZWF0ZRIbLmNvbG9ueS5Db2xvbnlDcmVh",
            "dGVSZXF1ZXN0GhIuY29sb255LkNvbG9ueURhdGEiABI7CgZVcGRhdGUSGy5j",
            "b2xvbnkuQ29sb255VXBkYXRlUmVxdWVzdBoSLmNvbG9ueS5Db2xvbnlEYXRh",
            "IgASNQoDR2V0EhguY29sb255LkNvbG9ueUdldFJlcXVlc3QaEi5jb2xvbnku",
            "Q29sb255RGF0YSIAEkQKBk1vZFNldBIcLmNvbG9ueS5Db2xvbnlNb2RzU2V0",
            "UmVxdWVzdBoaLmNvbG9ueS5Db2xvbnlNb2RzU2V0UmVwbHkiABJRCgtUcmFk",
            "YWJsZVNldBIgLmNvbG9ueS5Db2xvbnlUcmFkYWJsZVNldFJlcXVlc3QaHi5j",
            "b2xvbnkuQ29sb255VHJhZGFibGVTZXRSZXBseSIAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Tradable.TradableReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Colony.PlatformEnum), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Colony.ColonyData), global::Colony.ColonyData.Parser, new[]{ "ColonyId", "Name", "FactionName", "MapId", "Tick", "UsedDevMode", "GameVersion", "Platform", "CreateDate", "Seed", "Location" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Colony.ColonyCreateRequest), global::Colony.ColonyCreateRequest.Parser, new[]{ "ClientBindId", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Colony.ColonyUpdateRequest), global::Colony.ColonyUpdateRequest.Parser, new[]{ "ClientBindId", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Colony.ColonyGetRequest), global::Colony.ColonyGetRequest.Parser, new[]{ "ClientBindId", "ColonyId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Colony.ColonyModsSetRequest), global::Colony.ColonyModsSetRequest.Parser, new[]{ "ClientBindId", "ColonyId", "ModName" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Colony.ColonyModsSetReply), global::Colony.ColonyModsSetReply.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Colony.ColonyTradableSetRequest), global::Colony.ColonyTradableSetRequest.Parser, new[]{ "ClientBindId", "ColonyId", "Item", "FinalPacket" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Colony.ColonyTradableSetReply), global::Colony.ColonyTradableSetReply.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PlatformEnum {
    [pbr::OriginalName("Unknown")] Unknown = 0,
    [pbr::OriginalName("Windows")] Windows = 1,
    [pbr::OriginalName("Linux")] Linux = 2,
    [pbr::OriginalName("Mac")] Mac = 3,
  }

  #endregion

  #region Messages
  public sealed partial class ColonyData : pb::IMessage<ColonyData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ColonyData> _parser = new pb::MessageParser<ColonyData>(() => new ColonyData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ColonyData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Colony.ColonyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyData(ColonyData other) : this() {
      colonyId_ = other.colonyId_;
      name_ = other.name_;
      factionName_ = other.factionName_;
      mapId_ = other.mapId_;
      tick_ = other.tick_;
      usedDevMode_ = other.usedDevMode_;
      gameVersion_ = other.gameVersion_;
      platform_ = other.platform_;
      createDate_ = other.createDate_;
      seed_ = other.seed_;
      location_ = other.location_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyData Clone() {
      return new ColonyData(this);
    }

    /// <summary>Field number for the "ColonyId" field.</summary>
    public const int ColonyIdFieldNumber = 1;
    private string colonyId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ColonyId {
      get { return colonyId_; }
      set {
        colonyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FactionName" field.</summary>
    public const int FactionNameFieldNumber = 3;
    private string factionName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FactionName {
      get { return factionName_; }
      set {
        factionName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "MapId" field.</summary>
    public const int MapIdFieldNumber = 9;
    private int mapId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MapId {
      get { return mapId_; }
      set {
        mapId_ = value;
      }
    }

    /// <summary>Field number for the "Tick" field.</summary>
    public const int TickFieldNumber = 4;
    private int tick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Tick {
      get { return tick_; }
      set {
        tick_ = value;
      }
    }

    /// <summary>Field number for the "UsedDevMode" field.</summary>
    public const int UsedDevModeFieldNumber = 5;
    private bool usedDevMode_;
    /// <summary>
    /// This is a fuse, once blown, it cannot be unset.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool UsedDevMode {
      get { return usedDevMode_; }
      set {
        usedDevMode_ = value;
      }
    }

    /// <summary>Field number for the "GameVersion" field.</summary>
    public const int GameVersionFieldNumber = 6;
    private string gameVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GameVersion {
      get { return gameVersion_; }
      set {
        gameVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Platform" field.</summary>
    public const int PlatformFieldNumber = 7;
    private global::Colony.PlatformEnum platform_ = global::Colony.PlatformEnum.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Colony.PlatformEnum Platform {
      get { return platform_; }
      set {
        platform_ = value;
      }
    }

    /// <summary>Field number for the "CreateDate" field.</summary>
    public const int CreateDateFieldNumber = 8;
    private long createDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CreateDate {
      get { return createDate_; }
      set {
        createDate_ = value;
      }
    }

    /// <summary>Field number for the "Seed" field.</summary>
    public const int SeedFieldNumber = 10;
    private string seed_ = "";
    /// <summary>
    /// The world seed
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Seed {
      get { return seed_; }
      set {
        seed_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Location" field.</summary>
    public const int LocationFieldNumber = 11;
    private string location_ = "";
    /// <summary>
    ///X,Y of colony on map
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Location {
      get { return location_; }
      set {
        location_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ColonyData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ColonyData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ColonyId != other.ColonyId) return false;
      if (Name != other.Name) return false;
      if (FactionName != other.FactionName) return false;
      if (MapId != other.MapId) return false;
      if (Tick != other.Tick) return false;
      if (UsedDevMode != other.UsedDevMode) return false;
      if (GameVersion != other.GameVersion) return false;
      if (Platform != other.Platform) return false;
      if (CreateDate != other.CreateDate) return false;
      if (Seed != other.Seed) return false;
      if (Location != other.Location) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ColonyId.Length != 0) hash ^= ColonyId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (FactionName.Length != 0) hash ^= FactionName.GetHashCode();
      if (MapId != 0) hash ^= MapId.GetHashCode();
      if (Tick != 0) hash ^= Tick.GetHashCode();
      if (UsedDevMode != false) hash ^= UsedDevMode.GetHashCode();
      if (GameVersion.Length != 0) hash ^= GameVersion.GetHashCode();
      if (Platform != global::Colony.PlatformEnum.Unknown) hash ^= Platform.GetHashCode();
      if (CreateDate != 0L) hash ^= CreateDate.GetHashCode();
      if (Seed.Length != 0) hash ^= Seed.GetHashCode();
      if (Location.Length != 0) hash ^= Location.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ColonyId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ColonyId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (FactionName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FactionName);
      }
      if (Tick != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Tick);
      }
      if (UsedDevMode != false) {
        output.WriteRawTag(40);
        output.WriteBool(UsedDevMode);
      }
      if (GameVersion.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(GameVersion);
      }
      if (Platform != global::Colony.PlatformEnum.Unknown) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Platform);
      }
      if (CreateDate != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(CreateDate);
      }
      if (MapId != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(MapId);
      }
      if (Seed.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Seed);
      }
      if (Location.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Location);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ColonyId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ColonyId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (FactionName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FactionName);
      }
      if (Tick != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Tick);
      }
      if (UsedDevMode != false) {
        output.WriteRawTag(40);
        output.WriteBool(UsedDevMode);
      }
      if (GameVersion.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(GameVersion);
      }
      if (Platform != global::Colony.PlatformEnum.Unknown) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Platform);
      }
      if (CreateDate != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(CreateDate);
      }
      if (MapId != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(MapId);
      }
      if (Seed.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Seed);
      }
      if (Location.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Location);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ColonyId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ColonyId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (FactionName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FactionName);
      }
      if (MapId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MapId);
      }
      if (Tick != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Tick);
      }
      if (UsedDevMode != false) {
        size += 1 + 1;
      }
      if (GameVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GameVersion);
      }
      if (Platform != global::Colony.PlatformEnum.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Platform);
      }
      if (CreateDate != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CreateDate);
      }
      if (Seed.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Seed);
      }
      if (Location.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Location);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ColonyData other) {
      if (other == null) {
        return;
      }
      if (other.ColonyId.Length != 0) {
        ColonyId = other.ColonyId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.FactionName.Length != 0) {
        FactionName = other.FactionName;
      }
      if (other.MapId != 0) {
        MapId = other.MapId;
      }
      if (other.Tick != 0) {
        Tick = other.Tick;
      }
      if (other.UsedDevMode != false) {
        UsedDevMode = other.UsedDevMode;
      }
      if (other.GameVersion.Length != 0) {
        GameVersion = other.GameVersion;
      }
      if (other.Platform != global::Colony.PlatformEnum.Unknown) {
        Platform = other.Platform;
      }
      if (other.CreateDate != 0L) {
        CreateDate = other.CreateDate;
      }
      if (other.Seed.Length != 0) {
        Seed = other.Seed;
      }
      if (other.Location.Length != 0) {
        Location = other.Location;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ColonyId = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            FactionName = input.ReadString();
            break;
          }
          case 32: {
            Tick = input.ReadInt32();
            break;
          }
          case 40: {
            UsedDevMode = input.ReadBool();
            break;
          }
          case 50: {
            GameVersion = input.ReadString();
            break;
          }
          case 56: {
            Platform = (global::Colony.PlatformEnum) input.ReadEnum();
            break;
          }
          case 64: {
            CreateDate = input.ReadInt64();
            break;
          }
          case 72: {
            MapId = input.ReadInt32();
            break;
          }
          case 82: {
            Seed = input.ReadString();
            break;
          }
          case 90: {
            Location = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ColonyId = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            FactionName = input.ReadString();
            break;
          }
          case 32: {
            Tick = input.ReadInt32();
            break;
          }
          case 40: {
            UsedDevMode = input.ReadBool();
            break;
          }
          case 50: {
            GameVersion = input.ReadString();
            break;
          }
          case 56: {
            Platform = (global::Colony.PlatformEnum) input.ReadEnum();
            break;
          }
          case 64: {
            CreateDate = input.ReadInt64();
            break;
          }
          case 72: {
            MapId = input.ReadInt32();
            break;
          }
          case 82: {
            Seed = input.ReadString();
            break;
          }
          case 90: {
            Location = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ColonyCreateRequest : pb::IMessage<ColonyCreateRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ColonyCreateRequest> _parser = new pb::MessageParser<ColonyCreateRequest>(() => new ColonyCreateRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ColonyCreateRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Colony.ColonyReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyCreateRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyCreateRequest(ColonyCreateRequest other) : this() {
      clientBindId_ = other.clientBindId_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyCreateRequest Clone() {
      return new ColonyCreateRequest(this);
    }

    /// <summary>Field number for the "ClientBindId" field.</summary>
    public const int ClientBindIdFieldNumber = 1;
    private string clientBindId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientBindId {
      get { return clientBindId_; }
      set {
        clientBindId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 2;
    private global::Colony.ColonyData data_;
    /// <summary>
    /// Certain fields from ColonyData will be ignored
    /// during creation of the colony such as ColonyId and CreateDate.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Colony.ColonyData Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ColonyCreateRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ColonyCreateRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientBindId != other.ClientBindId) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientBindId.Length != 0) hash ^= ClientBindId.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientBindId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientBindId);
      }
      if (data_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientBindId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientBindId);
      }
      if (data_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ClientBindId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientBindId);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ColonyCreateRequest other) {
      if (other == null) {
        return;
      }
      if (other.ClientBindId.Length != 0) {
        ClientBindId = other.ClientBindId;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Colony.ColonyData();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ClientBindId = input.ReadString();
            break;
          }
          case 18: {
            if (data_ == null) {
              Data = new global::Colony.ColonyData();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ClientBindId = input.ReadString();
            break;
          }
          case 18: {
            if (data_ == null) {
              Data = new global::Colony.ColonyData();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ColonyUpdateRequest : pb::IMessage<ColonyUpdateRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ColonyUpdateRequest> _parser = new pb::MessageParser<ColonyUpdateRequest>(() => new ColonyUpdateRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ColonyUpdateRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Colony.ColonyReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyUpdateRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyUpdateRequest(ColonyUpdateRequest other) : this() {
      clientBindId_ = other.clientBindId_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyUpdateRequest Clone() {
      return new ColonyUpdateRequest(this);
    }

    /// <summary>Field number for the "ClientBindId" field.</summary>
    public const int ClientBindIdFieldNumber = 1;
    private string clientBindId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientBindId {
      get { return clientBindId_; }
      set {
        clientBindId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 3;
    private global::Colony.ColonyData data_;
    /// <summary>
    /// Certain fields from ColonyData will be ignored
    /// during update of the colony such as ColonyId, Platform and CreateDate.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Colony.ColonyData Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ColonyUpdateRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ColonyUpdateRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientBindId != other.ClientBindId) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientBindId.Length != 0) hash ^= ClientBindId.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientBindId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientBindId);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientBindId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientBindId);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ClientBindId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientBindId);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ColonyUpdateRequest other) {
      if (other == null) {
        return;
      }
      if (other.ClientBindId.Length != 0) {
        ClientBindId = other.ClientBindId;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Colony.ColonyData();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ClientBindId = input.ReadString();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::Colony.ColonyData();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ClientBindId = input.ReadString();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::Colony.ColonyData();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ColonyGetRequest : pb::IMessage<ColonyGetRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ColonyGetRequest> _parser = new pb::MessageParser<ColonyGetRequest>(() => new ColonyGetRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ColonyGetRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Colony.ColonyReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyGetRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyGetRequest(ColonyGetRequest other) : this() {
      clientBindId_ = other.clientBindId_;
      colonyId_ = other.colonyId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyGetRequest Clone() {
      return new ColonyGetRequest(this);
    }

    /// <summary>Field number for the "ClientBindId" field.</summary>
    public const int ClientBindIdFieldNumber = 1;
    private string clientBindId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientBindId {
      get { return clientBindId_; }
      set {
        clientBindId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ColonyId" field.</summary>
    public const int ColonyIdFieldNumber = 2;
    private string colonyId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ColonyId {
      get { return colonyId_; }
      set {
        colonyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ColonyGetRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ColonyGetRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientBindId != other.ClientBindId) return false;
      if (ColonyId != other.ColonyId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientBindId.Length != 0) hash ^= ClientBindId.GetHashCode();
      if (ColonyId.Length != 0) hash ^= ColonyId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientBindId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientBindId);
      }
      if (ColonyId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ColonyId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientBindId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientBindId);
      }
      if (ColonyId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ColonyId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ClientBindId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientBindId);
      }
      if (ColonyId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ColonyId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ColonyGetRequest other) {
      if (other == null) {
        return;
      }
      if (other.ClientBindId.Length != 0) {
        ClientBindId = other.ClientBindId;
      }
      if (other.ColonyId.Length != 0) {
        ColonyId = other.ColonyId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ClientBindId = input.ReadString();
            break;
          }
          case 18: {
            ColonyId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ClientBindId = input.ReadString();
            break;
          }
          case 18: {
            ColonyId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ColonyModsSetRequest : pb::IMessage<ColonyModsSetRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ColonyModsSetRequest> _parser = new pb::MessageParser<ColonyModsSetRequest>(() => new ColonyModsSetRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ColonyModsSetRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Colony.ColonyReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyModsSetRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyModsSetRequest(ColonyModsSetRequest other) : this() {
      clientBindId_ = other.clientBindId_;
      colonyId_ = other.colonyId_;
      modName_ = other.modName_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyModsSetRequest Clone() {
      return new ColonyModsSetRequest(this);
    }

    /// <summary>Field number for the "ClientBindId" field.</summary>
    public const int ClientBindIdFieldNumber = 1;
    private string clientBindId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientBindId {
      get { return clientBindId_; }
      set {
        clientBindId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ColonyId" field.</summary>
    public const int ColonyIdFieldNumber = 2;
    private string colonyId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ColonyId {
      get { return colonyId_; }
      set {
        colonyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ModName" field.</summary>
    public const int ModNameFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_modName_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> modName_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ModName {
      get { return modName_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ColonyModsSetRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ColonyModsSetRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientBindId != other.ClientBindId) return false;
      if (ColonyId != other.ColonyId) return false;
      if(!modName_.Equals(other.modName_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientBindId.Length != 0) hash ^= ClientBindId.GetHashCode();
      if (ColonyId.Length != 0) hash ^= ColonyId.GetHashCode();
      hash ^= modName_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientBindId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientBindId);
      }
      if (ColonyId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ColonyId);
      }
      modName_.WriteTo(output, _repeated_modName_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientBindId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientBindId);
      }
      if (ColonyId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ColonyId);
      }
      modName_.WriteTo(ref output, _repeated_modName_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ClientBindId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientBindId);
      }
      if (ColonyId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ColonyId);
      }
      size += modName_.CalculateSize(_repeated_modName_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ColonyModsSetRequest other) {
      if (other == null) {
        return;
      }
      if (other.ClientBindId.Length != 0) {
        ClientBindId = other.ClientBindId;
      }
      if (other.ColonyId.Length != 0) {
        ColonyId = other.ColonyId;
      }
      modName_.Add(other.modName_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ClientBindId = input.ReadString();
            break;
          }
          case 18: {
            ColonyId = input.ReadString();
            break;
          }
          case 26: {
            modName_.AddEntriesFrom(input, _repeated_modName_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ClientBindId = input.ReadString();
            break;
          }
          case 18: {
            ColonyId = input.ReadString();
            break;
          }
          case 26: {
            modName_.AddEntriesFrom(ref input, _repeated_modName_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ColonyModsSetReply : pb::IMessage<ColonyModsSetReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ColonyModsSetReply> _parser = new pb::MessageParser<ColonyModsSetReply>(() => new ColonyModsSetReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ColonyModsSetReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Colony.ColonyReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyModsSetReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyModsSetReply(ColonyModsSetReply other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyModsSetReply Clone() {
      return new ColonyModsSetReply(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ColonyModsSetReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ColonyModsSetReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ColonyModsSetReply other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class ColonyTradableSetRequest : pb::IMessage<ColonyTradableSetRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ColonyTradableSetRequest> _parser = new pb::MessageParser<ColonyTradableSetRequest>(() => new ColonyTradableSetRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ColonyTradableSetRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Colony.ColonyReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyTradableSetRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyTradableSetRequest(ColonyTradableSetRequest other) : this() {
      clientBindId_ = other.clientBindId_;
      colonyId_ = other.colonyId_;
      item_ = other.item_.Clone();
      finalPacket_ = other.finalPacket_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyTradableSetRequest Clone() {
      return new ColonyTradableSetRequest(this);
    }

    /// <summary>Field number for the "ClientBindId" field.</summary>
    public const int ClientBindIdFieldNumber = 1;
    private string clientBindId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientBindId {
      get { return clientBindId_; }
      set {
        clientBindId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ColonyId" field.</summary>
    public const int ColonyIdFieldNumber = 2;
    private string colonyId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ColonyId {
      get { return colonyId_; }
      set {
        colonyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "item" field.</summary>
    public const int ItemFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Tradable.ColonyTradable> _repeated_item_codec
        = pb::FieldCodec.ForMessage(26, global::Tradable.ColonyTradable.Parser);
    private readonly pbc::RepeatedField<global::Tradable.ColonyTradable> item_ = new pbc::RepeatedField<global::Tradable.ColonyTradable>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Tradable.ColonyTradable> Item {
      get { return item_; }
    }

    /// <summary>Field number for the "FinalPacket" field.</summary>
    public const int FinalPacketFieldNumber = 10;
    private bool finalPacket_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool FinalPacket {
      get { return finalPacket_; }
      set {
        finalPacket_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ColonyTradableSetRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ColonyTradableSetRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientBindId != other.ClientBindId) return false;
      if (ColonyId != other.ColonyId) return false;
      if(!item_.Equals(other.item_)) return false;
      if (FinalPacket != other.FinalPacket) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientBindId.Length != 0) hash ^= ClientBindId.GetHashCode();
      if (ColonyId.Length != 0) hash ^= ColonyId.GetHashCode();
      hash ^= item_.GetHashCode();
      if (FinalPacket != false) hash ^= FinalPacket.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientBindId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientBindId);
      }
      if (ColonyId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ColonyId);
      }
      item_.WriteTo(output, _repeated_item_codec);
      if (FinalPacket != false) {
        output.WriteRawTag(80);
        output.WriteBool(FinalPacket);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientBindId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientBindId);
      }
      if (ColonyId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ColonyId);
      }
      item_.WriteTo(ref output, _repeated_item_codec);
      if (FinalPacket != false) {
        output.WriteRawTag(80);
        output.WriteBool(FinalPacket);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ClientBindId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientBindId);
      }
      if (ColonyId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ColonyId);
      }
      size += item_.CalculateSize(_repeated_item_codec);
      if (FinalPacket != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ColonyTradableSetRequest other) {
      if (other == null) {
        return;
      }
      if (other.ClientBindId.Length != 0) {
        ClientBindId = other.ClientBindId;
      }
      if (other.ColonyId.Length != 0) {
        ColonyId = other.ColonyId;
      }
      item_.Add(other.item_);
      if (other.FinalPacket != false) {
        FinalPacket = other.FinalPacket;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ClientBindId = input.ReadString();
            break;
          }
          case 18: {
            ColonyId = input.ReadString();
            break;
          }
          case 26: {
            item_.AddEntriesFrom(input, _repeated_item_codec);
            break;
          }
          case 80: {
            FinalPacket = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ClientBindId = input.ReadString();
            break;
          }
          case 18: {
            ColonyId = input.ReadString();
            break;
          }
          case 26: {
            item_.AddEntriesFrom(ref input, _repeated_item_codec);
            break;
          }
          case 80: {
            FinalPacket = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ColonyTradableSetReply : pb::IMessage<ColonyTradableSetReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ColonyTradableSetReply> _parser = new pb::MessageParser<ColonyTradableSetReply>(() => new ColonyTradableSetReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ColonyTradableSetReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Colony.ColonyReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyTradableSetReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyTradableSetReply(ColonyTradableSetReply other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColonyTradableSetReply Clone() {
      return new ColonyTradableSetReply(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ColonyTradableSetReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ColonyTradableSetReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ColonyTradableSetReply other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
