// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: order.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Order {

  /// <summary>Holder for reflection information generated from order.proto</summary>
  public static partial class OrderReflection {

    #region Descriptor
    /// <summary>File descriptor for order.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OrderReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtvcmRlci5wcm90bxIFb3JkZXIiPwoJT3JkZXJJdGVtEhAKCEl0ZW1Db2Rl",
            "GAEgASgJEhAKCFF1YW50aXR5GAIgASgFEg4KBkhlYWx0aBgDIAEoAiKxAQoM",
            "T3JkZXJSZXF1ZXN0EhQKDENsaWVudEJpbmRJZBgBIAEoCRIQCghDb2xvbnlJ",
            "ZBgCIAEoCRISCgpDb2xvbnlUaWNrGAMgASgFEiQKCldhbnRUb1NlbGwYBCAD",
            "KAsyEC5vcmRlci5PcmRlckl0ZW0SIwoJV2FudFRvQnV5GAUgAygLMhAub3Jk",
            "ZXIuT3JkZXJJdGVtEhoKEkludmVudG9yeVByb21pc2VJZBgGIAEoCSKBAQoK",
            "T3JkZXJSZXBseRIPCgdPcmRlcklkGAEgASgJEikKBnN0YXR1cxgCIAEoDjIZ",
            "Lm9yZGVyLk9yZGVyUmVxdWVzdFN0YXR1cxIlCgt1bmF2YWlsYWJsZRgDIAMo",
            "CzIQLm9yZGVyLk9yZGVySXRlbRIQCghyZWZ1bmRlZBgEIAEoBSJNChJPcmRl",
            "clN0YXR1c1JlcXVlc3QSFAoMQ2xpZW50QmluZElkGAEgASgJEhAKCENvbG9u",
            "eUlkGAIgASgJEg8KB09yZGVySWQYAyABKAkiNgoQT3JkZXJTdGF0dXNSZXBs",
            "eRIiCgZzdGF0dXMYASABKA4yEi5vcmRlci5PcmRlclN0YXR1cypIChJPcmRl",
            "clJlcXVlc3RTdGF0dXMSDAoIUmVqZWN0ZWQQABIPCgtBY2NlcHRlZEFsbBAB",
            "EhMKD0FjY2VwdGVkUGFydGlhbBACKlYKC09yZGVyU3RhdHVzEgoKBlBsYWNl",
            "ZBAAEhIKDk91dEZvckRlbGl2ZXJ5EAESDQoJRGVsaXZlcmVkEAISCgoGRmFp",
            "bGVkEAMSDAoIUmV2ZXJzZWQQBDI/CgxPcmRlclNlcnZpY2USLwoDR2V0EhMu",
            "b3JkZXIuT3JkZXJSZXF1ZXN0GhEub3JkZXIuT3JkZXJSZXBseSIAYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Order.OrderRequestStatus), typeof(global::Order.OrderStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Order.OrderItem), global::Order.OrderItem.Parser, new[]{ "ItemCode", "Quantity", "Health" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Order.OrderRequest), global::Order.OrderRequest.Parser, new[]{ "ClientBindId", "ColonyId", "ColonyTick", "WantToSell", "WantToBuy", "InventoryPromiseId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Order.OrderReply), global::Order.OrderReply.Parser, new[]{ "OrderId", "Status", "Unavailable", "Refunded" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Order.OrderStatusRequest), global::Order.OrderStatusRequest.Parser, new[]{ "ClientBindId", "ColonyId", "OrderId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Order.OrderStatusReply), global::Order.OrderStatusReply.Parser, new[]{ "Status" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum OrderRequestStatus {
    [pbr::OriginalName("Rejected")] Rejected = 0,
    [pbr::OriginalName("AcceptedAll")] AcceptedAll = 1,
    [pbr::OriginalName("AcceptedPartial")] AcceptedPartial = 2,
  }

  public enum OrderStatus {
    [pbr::OriginalName("Placed")] Placed = 0,
    [pbr::OriginalName("OutForDelivery")] OutForDelivery = 1,
    [pbr::OriginalName("Delivered")] Delivered = 2,
    [pbr::OriginalName("Failed")] Failed = 3,
    [pbr::OriginalName("Reversed")] Reversed = 4,
  }

  #endregion

  #region Messages
  public sealed partial class OrderItem : pb::IMessage<OrderItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderItem> _parser = new pb::MessageParser<OrderItem>(() => new OrderItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OrderItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Order.OrderReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderItem(OrderItem other) : this() {
      itemCode_ = other.itemCode_;
      quantity_ = other.quantity_;
      health_ = other.health_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderItem Clone() {
      return new OrderItem(this);
    }

    /// <summary>Field number for the "ItemCode" field.</summary>
    public const int ItemCodeFieldNumber = 1;
    private string itemCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ItemCode {
      get { return itemCode_; }
      set {
        itemCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Quantity" field.</summary>
    public const int QuantityFieldNumber = 2;
    private int quantity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Quantity {
      get { return quantity_; }
      set {
        quantity_ = value;
      }
    }

    /// <summary>Field number for the "Health" field.</summary>
    public const int HealthFieldNumber = 3;
    private float health_;
    /// <summary>
    /// Value between 0-100 representing the
    /// Remaining percentage hitpoints of this item
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Health {
      get { return health_; }
      set {
        health_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OrderItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OrderItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ItemCode != other.ItemCode) return false;
      if (Quantity != other.Quantity) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Health, other.Health)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ItemCode.Length != 0) hash ^= ItemCode.GetHashCode();
      if (Quantity != 0) hash ^= Quantity.GetHashCode();
      if (Health != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Health);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ItemCode.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ItemCode);
      }
      if (Quantity != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Quantity);
      }
      if (Health != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Health);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ItemCode.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ItemCode);
      }
      if (Quantity != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Quantity);
      }
      if (Health != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Health);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ItemCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemCode);
      }
      if (Quantity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quantity);
      }
      if (Health != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OrderItem other) {
      if (other == null) {
        return;
      }
      if (other.ItemCode.Length != 0) {
        ItemCode = other.ItemCode;
      }
      if (other.Quantity != 0) {
        Quantity = other.Quantity;
      }
      if (other.Health != 0F) {
        Health = other.Health;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ItemCode = input.ReadString();
            break;
          }
          case 16: {
            Quantity = input.ReadInt32();
            break;
          }
          case 29: {
            Health = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ItemCode = input.ReadString();
            break;
          }
          case 16: {
            Quantity = input.ReadInt32();
            break;
          }
          case 29: {
            Health = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OrderRequest : pb::IMessage<OrderRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderRequest> _parser = new pb::MessageParser<OrderRequest>(() => new OrderRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OrderRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Order.OrderReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderRequest(OrderRequest other) : this() {
      clientBindId_ = other.clientBindId_;
      colonyId_ = other.colonyId_;
      colonyTick_ = other.colonyTick_;
      wantToSell_ = other.wantToSell_.Clone();
      wantToBuy_ = other.wantToBuy_.Clone();
      inventoryPromiseId_ = other.inventoryPromiseId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderRequest Clone() {
      return new OrderRequest(this);
    }

    /// <summary>Field number for the "ClientBindId" field.</summary>
    public const int ClientBindIdFieldNumber = 1;
    private string clientBindId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ClientBindId {
      get { return clientBindId_; }
      set {
        clientBindId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ColonyId" field.</summary>
    public const int ColonyIdFieldNumber = 2;
    private string colonyId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ColonyId {
      get { return colonyId_; }
      set {
        colonyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ColonyTick" field.</summary>
    public const int ColonyTickFieldNumber = 3;
    private int colonyTick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ColonyTick {
      get { return colonyTick_; }
      set {
        colonyTick_ = value;
      }
    }

    /// <summary>Field number for the "WantToSell" field.</summary>
    public const int WantToSellFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Order.OrderItem> _repeated_wantToSell_codec
        = pb::FieldCodec.ForMessage(34, global::Order.OrderItem.Parser);
    private readonly pbc::RepeatedField<global::Order.OrderItem> wantToSell_ = new pbc::RepeatedField<global::Order.OrderItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Order.OrderItem> WantToSell {
      get { return wantToSell_; }
    }

    /// <summary>Field number for the "WantToBuy" field.</summary>
    public const int WantToBuyFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Order.OrderItem> _repeated_wantToBuy_codec
        = pb::FieldCodec.ForMessage(42, global::Order.OrderItem.Parser);
    private readonly pbc::RepeatedField<global::Order.OrderItem> wantToBuy_ = new pbc::RepeatedField<global::Order.OrderItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Order.OrderItem> WantToBuy {
      get { return wantToBuy_; }
    }

    /// <summary>Field number for the "InventoryPromiseId" field.</summary>
    public const int InventoryPromiseIdFieldNumber = 6;
    private string inventoryPromiseId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string InventoryPromiseId {
      get { return inventoryPromiseId_; }
      set {
        inventoryPromiseId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OrderRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OrderRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientBindId != other.ClientBindId) return false;
      if (ColonyId != other.ColonyId) return false;
      if (ColonyTick != other.ColonyTick) return false;
      if(!wantToSell_.Equals(other.wantToSell_)) return false;
      if(!wantToBuy_.Equals(other.wantToBuy_)) return false;
      if (InventoryPromiseId != other.InventoryPromiseId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientBindId.Length != 0) hash ^= ClientBindId.GetHashCode();
      if (ColonyId.Length != 0) hash ^= ColonyId.GetHashCode();
      if (ColonyTick != 0) hash ^= ColonyTick.GetHashCode();
      hash ^= wantToSell_.GetHashCode();
      hash ^= wantToBuy_.GetHashCode();
      if (InventoryPromiseId.Length != 0) hash ^= InventoryPromiseId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientBindId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientBindId);
      }
      if (ColonyId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ColonyId);
      }
      if (ColonyTick != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ColonyTick);
      }
      wantToSell_.WriteTo(output, _repeated_wantToSell_codec);
      wantToBuy_.WriteTo(output, _repeated_wantToBuy_codec);
      if (InventoryPromiseId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(InventoryPromiseId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientBindId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientBindId);
      }
      if (ColonyId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ColonyId);
      }
      if (ColonyTick != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ColonyTick);
      }
      wantToSell_.WriteTo(ref output, _repeated_wantToSell_codec);
      wantToBuy_.WriteTo(ref output, _repeated_wantToBuy_codec);
      if (InventoryPromiseId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(InventoryPromiseId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ClientBindId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientBindId);
      }
      if (ColonyId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ColonyId);
      }
      if (ColonyTick != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ColonyTick);
      }
      size += wantToSell_.CalculateSize(_repeated_wantToSell_codec);
      size += wantToBuy_.CalculateSize(_repeated_wantToBuy_codec);
      if (InventoryPromiseId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InventoryPromiseId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OrderRequest other) {
      if (other == null) {
        return;
      }
      if (other.ClientBindId.Length != 0) {
        ClientBindId = other.ClientBindId;
      }
      if (other.ColonyId.Length != 0) {
        ColonyId = other.ColonyId;
      }
      if (other.ColonyTick != 0) {
        ColonyTick = other.ColonyTick;
      }
      wantToSell_.Add(other.wantToSell_);
      wantToBuy_.Add(other.wantToBuy_);
      if (other.InventoryPromiseId.Length != 0) {
        InventoryPromiseId = other.InventoryPromiseId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ClientBindId = input.ReadString();
            break;
          }
          case 18: {
            ColonyId = input.ReadString();
            break;
          }
          case 24: {
            ColonyTick = input.ReadInt32();
            break;
          }
          case 34: {
            wantToSell_.AddEntriesFrom(input, _repeated_wantToSell_codec);
            break;
          }
          case 42: {
            wantToBuy_.AddEntriesFrom(input, _repeated_wantToBuy_codec);
            break;
          }
          case 50: {
            InventoryPromiseId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ClientBindId = input.ReadString();
            break;
          }
          case 18: {
            ColonyId = input.ReadString();
            break;
          }
          case 24: {
            ColonyTick = input.ReadInt32();
            break;
          }
          case 34: {
            wantToSell_.AddEntriesFrom(ref input, _repeated_wantToSell_codec);
            break;
          }
          case 42: {
            wantToBuy_.AddEntriesFrom(ref input, _repeated_wantToBuy_codec);
            break;
          }
          case 50: {
            InventoryPromiseId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OrderReply : pb::IMessage<OrderReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderReply> _parser = new pb::MessageParser<OrderReply>(() => new OrderReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OrderReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Order.OrderReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderReply(OrderReply other) : this() {
      orderId_ = other.orderId_;
      status_ = other.status_;
      unavailable_ = other.unavailable_.Clone();
      refunded_ = other.refunded_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderReply Clone() {
      return new OrderReply(this);
    }

    /// <summary>Field number for the "OrderId" field.</summary>
    public const int OrderIdFieldNumber = 1;
    private string orderId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OrderId {
      get { return orderId_; }
      set {
        orderId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private global::Order.OrderRequestStatus status_ = global::Order.OrderRequestStatus.Rejected;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Order.OrderRequestStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "unavailable" field.</summary>
    public const int UnavailableFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Order.OrderItem> _repeated_unavailable_codec
        = pb::FieldCodec.ForMessage(26, global::Order.OrderItem.Parser);
    private readonly pbc::RepeatedField<global::Order.OrderItem> unavailable_ = new pbc::RepeatedField<global::Order.OrderItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Order.OrderItem> Unavailable {
      get { return unavailable_; }
    }

    /// <summary>Field number for the "refunded" field.</summary>
    public const int RefundedFieldNumber = 4;
    private int refunded_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Refunded {
      get { return refunded_; }
      set {
        refunded_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OrderReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OrderReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrderId != other.OrderId) return false;
      if (Status != other.Status) return false;
      if(!unavailable_.Equals(other.unavailable_)) return false;
      if (Refunded != other.Refunded) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (OrderId.Length != 0) hash ^= OrderId.GetHashCode();
      if (Status != global::Order.OrderRequestStatus.Rejected) hash ^= Status.GetHashCode();
      hash ^= unavailable_.GetHashCode();
      if (Refunded != 0) hash ^= Refunded.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OrderId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OrderId);
      }
      if (Status != global::Order.OrderRequestStatus.Rejected) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      unavailable_.WriteTo(output, _repeated_unavailable_codec);
      if (Refunded != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Refunded);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OrderId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OrderId);
      }
      if (Status != global::Order.OrderRequestStatus.Rejected) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      unavailable_.WriteTo(ref output, _repeated_unavailable_codec);
      if (Refunded != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Refunded);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (OrderId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderId);
      }
      if (Status != global::Order.OrderRequestStatus.Rejected) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      size += unavailable_.CalculateSize(_repeated_unavailable_codec);
      if (Refunded != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Refunded);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OrderReply other) {
      if (other == null) {
        return;
      }
      if (other.OrderId.Length != 0) {
        OrderId = other.OrderId;
      }
      if (other.Status != global::Order.OrderRequestStatus.Rejected) {
        Status = other.Status;
      }
      unavailable_.Add(other.unavailable_);
      if (other.Refunded != 0) {
        Refunded = other.Refunded;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OrderId = input.ReadString();
            break;
          }
          case 16: {
            Status = (global::Order.OrderRequestStatus) input.ReadEnum();
            break;
          }
          case 26: {
            unavailable_.AddEntriesFrom(input, _repeated_unavailable_codec);
            break;
          }
          case 32: {
            Refunded = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            OrderId = input.ReadString();
            break;
          }
          case 16: {
            Status = (global::Order.OrderRequestStatus) input.ReadEnum();
            break;
          }
          case 26: {
            unavailable_.AddEntriesFrom(ref input, _repeated_unavailable_codec);
            break;
          }
          case 32: {
            Refunded = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OrderStatusRequest : pb::IMessage<OrderStatusRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderStatusRequest> _parser = new pb::MessageParser<OrderStatusRequest>(() => new OrderStatusRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OrderStatusRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Order.OrderReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderStatusRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderStatusRequest(OrderStatusRequest other) : this() {
      clientBindId_ = other.clientBindId_;
      colonyId_ = other.colonyId_;
      orderId_ = other.orderId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderStatusRequest Clone() {
      return new OrderStatusRequest(this);
    }

    /// <summary>Field number for the "ClientBindId" field.</summary>
    public const int ClientBindIdFieldNumber = 1;
    private string clientBindId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ClientBindId {
      get { return clientBindId_; }
      set {
        clientBindId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ColonyId" field.</summary>
    public const int ColonyIdFieldNumber = 2;
    private string colonyId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ColonyId {
      get { return colonyId_; }
      set {
        colonyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "OrderId" field.</summary>
    public const int OrderIdFieldNumber = 3;
    private string orderId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OrderId {
      get { return orderId_; }
      set {
        orderId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OrderStatusRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OrderStatusRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientBindId != other.ClientBindId) return false;
      if (ColonyId != other.ColonyId) return false;
      if (OrderId != other.OrderId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientBindId.Length != 0) hash ^= ClientBindId.GetHashCode();
      if (ColonyId.Length != 0) hash ^= ColonyId.GetHashCode();
      if (OrderId.Length != 0) hash ^= OrderId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientBindId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientBindId);
      }
      if (ColonyId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ColonyId);
      }
      if (OrderId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OrderId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientBindId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientBindId);
      }
      if (ColonyId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ColonyId);
      }
      if (OrderId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OrderId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ClientBindId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientBindId);
      }
      if (ColonyId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ColonyId);
      }
      if (OrderId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OrderStatusRequest other) {
      if (other == null) {
        return;
      }
      if (other.ClientBindId.Length != 0) {
        ClientBindId = other.ClientBindId;
      }
      if (other.ColonyId.Length != 0) {
        ColonyId = other.ColonyId;
      }
      if (other.OrderId.Length != 0) {
        OrderId = other.OrderId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ClientBindId = input.ReadString();
            break;
          }
          case 18: {
            ColonyId = input.ReadString();
            break;
          }
          case 26: {
            OrderId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ClientBindId = input.ReadString();
            break;
          }
          case 18: {
            ColonyId = input.ReadString();
            break;
          }
          case 26: {
            OrderId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OrderStatusReply : pb::IMessage<OrderStatusReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderStatusReply> _parser = new pb::MessageParser<OrderStatusReply>(() => new OrderStatusReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OrderStatusReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Order.OrderReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderStatusReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderStatusReply(OrderStatusReply other) : this() {
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderStatusReply Clone() {
      return new OrderStatusReply(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::Order.OrderStatus status_ = global::Order.OrderStatus.Placed;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Order.OrderStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OrderStatusReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OrderStatusReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != global::Order.OrderStatus.Placed) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Status != global::Order.OrderStatus.Placed) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Status != global::Order.OrderStatus.Placed) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Status != global::Order.OrderStatus.Placed) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OrderStatusReply other) {
      if (other == null) {
        return;
      }
      if (other.Status != global::Order.OrderStatus.Placed) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = (global::Order.OrderStatus) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Status = (global::Order.OrderStatus) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
